# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5051de33a418b41147355761a8f6b1dfac1855ddc6f23b0f518727120f36b439621da4806f8b1b73674aee5fabd238aa85163411bbc5434037da9cd16932148d

test:
  secret_key_base: 70d438321a72d858c65bcac5ffffaecd2c9924fc46a55796c14ea2f21c41bb55fb645bf1c1097a8065fef0f2fea936b7529531ec4f2babca363145e71cf24b09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
